New news
kursomir/markup2.0 pull request #15
Opened 2017-03-10 18:18 UTC by AgDust

Из отсебятины:
1. Уменьшил картинки чтобы было больше места для текста и сомтрелось органичнее
2. Не делал плавающую панель справа и кнопки навигации внизу т.к. они не нужны
3. Поднял заголовок так чтобы он был вровень с картинкой
4. Переместил дату вправо, так как ни под ни над заголовком она не очень как-то

2017-03-10 18:35 UTC, AgDust commented
Забыл прикрепить
![News](https://cloud.githubusercontent.com/assets/20019289/23808086/d5decc04-05e1-11e7-9cf8-351003463af5.png)

2017-03-10 18:44 UTC, mixty1 commented
#5 Список новостей
#8 Страница новости

2017-03-10 18:51 UTC, ZverArt commented
А не много получается пустого места?

2017-03-10 18:51 UTC, mixty1 commented
мне тоже кажется что слишком пусто

2017-03-10 18:54 UTC, basavind commented
а зачем в один пул 2 разных ишью :(

А если по вопросу — а зачем отсебятина? Мы же это уже обсуждали и пришли к какому-то общему решению, зачем было отсебятинку?

2017-03-10 18:54 UTC, mixty1 commented
может рекламы в сайдбар напихать :D

2017-03-10 18:55 UTC, mixty1 commented
@basavind  потому что этот пулл охватывает 2 ишью

2017-03-10 18:56 UTC, basavind commented
@mixty1 я вижу 2 коммита "finish read_news page" и "finish all_news page" — не судьба их разнести в 2 пула?

2017-03-10 18:56 UTC, basavind commented
"Не делал плавающую панель справа и кнопки навигации внизу т.к. они не нужны" — в честь чего?

2017-03-10 19:04 UTC, AgDust commented
А зачем они? Даты и так вынесены вправо,не думаю что будет особо много новостей в месяц чтобы имело смысл делать такую плавающую панель. Внизу и вовсе кнопка переключения по месяцам, это как? Надо как минимум что-то одно убрать, а лучше оставить просто ленту новостей без всего лишнего

2017-03-10 19:04 UTC, basavind requested changes
Не вижу убедительных аргументов отступать от решения дизайнера, тем более в пользу субъективного мнения.

2017-03-10 19:05 UTC, AgDust commented
Пустого места меньше не станет если добавить панель справа.

По поводу двух разных пуллов не подумал, изменений немного поэтому не стал выносить...

2017-03-10 19:06 UTC, AgDust commented
Отсебятина затем что при верстке все немного по-другому воспринималось. Если не стоило я сейчас все сделаю как нарисовано, там недолго

2017-03-10 19:50 UTC, gomzz commented
Ребят, насчет пустого места, используется удобная ширина столбца, чтобы можно было без проблем читать и не теряться в тексте, не надо его как-то расширять на весь экран, глаза сломаешь. Зря убрали навигацию, это систематизирование данных, большая бесконечная лента ни к чему. Снизу лишь была листалка, обычная пагинация - вперед, назад, только назвывалась месяц туда - месяц сюда. Про плавающую панель я нигде не указывал, сомневаюсь что она нужна.

2017-03-10 19:54 UTC, gomzz commented
Насчет уменьшения картинок, выглядит врое нормуль.

2017-03-10 20:04 UTC, AgDust commented
![Fixed](https://cloud.githubusercontent.com/assets/20019289/23811182/4fffcfea-05ee-11e7-9f56-a70b40a7412c.png)

2017-03-10 20:12 UTC, gomzz commented
Давай уменьшим картинки, у тебя нормально получилось, сделаем их шириной  в одну треть текстовой колонки(580) минус поле(20) = 180.

2017-03-10 20:23 UTC, AgDust commented
![Fixed](https://cloud.githubusercontent.com/assets/20019289/23811796/eeb48e94-05f0-11e7-8683-86c3b4df8759.png)

2017-03-10 20:24 UTC, gomzz commented
А по поводу пагинации тут логика простая. В курсах, допустим, у нас нет пагинации, как только мы отфильтруем (наука-направление) у нас как бы один блок данных по нашему запросу и мы их просто подгружаем по мере прокрутки. С новостями же другая тема, тут каждый месяц свой блок, ясен пень, что новосте может быть не много, но исторически так сложилось, что людям проще фрагментировать такую информацию, разбив ее на блоки.

2017-03-10 20:27 UTC, gomzz commented
Да,  дату только подтянуть до края картинки, минус margin-top или еще как.

2017-03-10 20:30 UTC, AgDust commented
Меню справа копирует плавающую панель на сайте в разделе "команда", там она фиксирована и переключается по мере прокрутки, что подразумевает или длинную страницу или ленту. Здесь же и пагинация и лента вместе

Окс, я не спорю. Дату пофиксил

2017-03-10 20:32 UTC, gomzz commented
По поводу плавающей панельки я прям хз.. По мне лучше статично, если будет плавающая - пагинация в принципе не нужна.

2017-03-10 20:36 UTC, gomzz commented
о проекте и комана будут перерабатываться. Не знаю как все, мне как то не хочется пихать всякую движующуюся лабуду в диз. Лучше использовать маленькие приятные анимашки на табах, кнопках, кртинках.

2017-03-11 13:13 UTC, mixty1 commented
может все-такие картинки по больше сделать, как изначально было?

2024-02-12 11:20 UTC, closed without merging